### ISSUE TITLE
Itach Relay

### ISSUE THREAD

**Issue by kusanghi** [plarsson/com.globalcache#1]
You can write more Itach Contact Closure (Relay) controllers? Thanks

**Comment by plarsson** [comment]
Yes it can be added. Can you help testing? I don't have that device

**Comment by kusanghi** [comment]
Thanks for the reply, I can help you test, Any request, I will help you.
Thanks.

**Comment by plarsson** [comment]
Added support for cc (relay), please have a look.

**Comment by kentaclub** [comment]
Thanks for the support device
It seems I am having a problem to not recognize the device after adding success.
![1](https://user-images.githubusercontent.com/42129672/46590469-b8b12380-cadd-11e8-85e1-879262a52839.png)

I try to send the command in the flow, get the error
![3](https://user-images.githubusercontent.com/42129672/46590487-d4b4c500-cadd-11e8-9c56-ab8a30c3d8cb.jpg)

This is a connection and send a command from the Itach software
Comand String : `setstate,1:1,1` or `setstate,1:1,0`
![2](https://user-images.githubusercontent.com/42129672/46590533-34ab6b80-cade-11e8-8779-b504aa24c0e8.jpg)

**Comment by kentaclub** [comment]
Thanks for the support device
Device after adding success.
![1](https://user-images.githubusercontent.com/42129672/46590469-b8b12380-cadd-11e8-85e1-879262a52839.png)

I try to send the command in the flow, get the error
![3](https://user-images.githubusercontent.com/42129672/46590487-d4b4c500-cadd-11e8-9c56-ab8a30c3d8cb.jpg)

This is a connection and send a command from the Itach software
Comand String : `setstate,1:1,1` or `setstate,1:1,0`
![2](https://user-images.githubusercontent.com/42129672/46590533-34ab6b80-cade-11e8-8779-b504aa24c0e8.jpg)

**Comment by kusanghi** [comment]
Thanks for the support device, I created a Pull Request, fixing the 20 line error in Device.js
`this._sendProntoCode(connectorAddress, outputState)`
![3](https://user-images.githubusercontent.com/42129672/46590487-d4b4c500-cadd-11e8-9c56-ab8a30c3d8cb.jpg)
change
`this._sendState(connectorAddress, outputState)`
![4](https://user-images.githubusercontent.com/42129672/46591621-1e091280-cae6-11e8-8f61-1586c2f84cc4.jpg)

It won't get an error when sending a command in the flow, and works well.

**Comment by plarsson** [comment]
Great, thank you.  It's merged now

**Comment by plarsson** [comment]
I was thinking that possible the relay version could be supported as switches instead or in addition to this. Will see for a future version.  

Right now it works similar as the IR and Serial
