### ISSUE TITLE
WF2SL added but not shown in flow editor

### ISSUE THREAD

**Issue by moekdegroot** [plarsson/com.globalcache#3]
Hi @plarsson , I just installed your appstore release version of the app but something strange is going on.
I can add the device in the devices tab and appears in the zone I installed it in but when I want to use the device in a flow it is not listed in the flow editor.
Any idea what's wrong?
![devices tab](https://user-images.githubusercontent.com/16590284/47534754-dbeb1980-d8b8-11e8-9bdb-e012fe5b6041.png)
![flow editor](https://user-images.githubusercontent.com/16590284/47534763-e0afcd80-d8b8-11e8-8515-57e1de13e5af.png)

**Comment by plarsson** [comment]
Hi, I haven't seen this issue. Can you try to install the latest master from github using the developer way 'athom app run -c' or 'athom app create -c' eg. with the clean command. This might help get rid of any old stuff. And if that works, try the app store install.

I changed the devices to 6 (separated ip from wf) instead of 3 if that could have caused something?

**Comment by moekdegroot** [comment]
I removed the app and tried installing with "run" and "create" but get the following after install:
![screen shot 2018-10-27 at 00 19 04](https://user-images.githubusercontent.com/16590284/47594957-1cf93180-d97e-11e8-95a7-f11605adc037.png)
So I'm affraid I can't give you any logs...
Are you sure the device has flowcards?
Again, I don't have any coding skills. Just mentioning some stuff I read on the forums over the years ;)

EDIT: forgot to add that after doing the above I installed via the appstore as you asked. But still no go.

EDIT2: just installed the latest version you created on oct 7th and everything is working again.
So I think we can rule out that something within my setup is causing it.
If there's anything else I can do, please let me know.

Thanks, Moek

**Comment by plarsson** [comment]
Yes you're right, it's the flows. I missed to add them as filter when I splitted out WF devices.

**Comment by plarsson** [comment]
I pushed a fix, please test the latest version from master when you have time.

**Comment by moekdegroot** [comment]
Hi @plarsson , I removed the app from homey, installed the master and it's showing up in the flow editor.
Thanks for the quick fix!
P.s. Don't forget your donate button ;)

**Comment by moekdegroot** [comment]
Oops, forgot to close the issue...

**Comment by plarsson** [comment]
Great, I'll submit a new version to app store. There is a donate button on the app store page ;)
Thanks for the bug report

**Comment by moekdegroot** [comment]
Cool, thx!
Yeah, found the donate button this afternoon and bought you some beers:) 
Thanks again!

**Comment by plarsson** [comment]
Thank you! 🍺

1.0.1 is out in the store already, Athom approved it very fast 👍

**Comment by moekdegroot** [comment]
You're very welcome.
Just installed the latest app store version and all is a-ok!
Thanks!
