### ISSUE TITLE
I can't do paste code on Homey app

### ISSUE THREAD

**Issue by FLH-Henry** [plarsson/com.globalcache#4]
Hi Peter,
I can't paste the Global Cache code on the Homey  app interface.
Refer to the figure below.
![screenshot_20190122-113745](https://user-images.githubusercontent.com/16569175/51827600-c3a9f100-2324-11e9-933a-4376e2c7a8e5.png)

Please help,
Many Thanks.

**Comment by plarsson** [comment]
Hi, yes it will be fixed. The app was initially designed for Homey 1.x versions. 

The first solution is to use the Athom web API so we can edit the codes etc. through a regular browser on computer. 

Secondly I might do some specific mobile UI, but not sure if it makes any sense to work with long pronto codes there. 

I'm currently working on the implementation for the web API. I can't promise any release date yet, as it also depends on Athom, when they enable the web API for 3rd party developers.

**Comment by plarsson** [comment]
version 1.1.0 now has a better editor
