### ISSUE TITLE
Help with serial cmd

### ISSUE THREAD

**Issue by davidkm123** [plarsson/com.globalcache#5]
Hi, can you please me help with string for command? I want sent command as in picture.

I try any combinations:

            { "name": "on0", "value": "*Z01ON" },
            { "name": "on1", "value": "*Z01ON\u000D\u000A" },
            { "name": "on2", "value": "\u002A*Z01ON\u000D" },
            { "name": "on3", "value": "\u002A\u002AZ01ON\u000D" },
            { "name": "on4", "value": "\u002A\u002AZ01ON" },
            { "name": "on5", "value": "\u002A\u002A\u005A\u0030\u0031\u004F\u004E" },
            { "name": "on6", "value": "\u002A\u002A\u005A\u0030\u0031\u004F\u004E\u000D" },
            { "name": "on7", "value": "*Z01ON0D" },

Thx

David

![2019-04-03_22-13-36](https://user-images.githubusercontent.com/38560286/55510115-cd6e0e80-565d-11e9-8640-9724aab7a00f.jpg)

**Comment by plarsson** [comment]
Hi, If you want to send the string ```*Z01ON``` with a CR it should be ```*Z01ON\u000D```
Have you verified that you're using the correct baud rate and parity settings?

**Comment by plarsson** [comment]
Hi is this still a problem?

**Comment by davidkm123** [comment]
Hi, yes, i have stil problem :-( is any way to view logs?

D.

23. 9. 2019 v 22:36, Peter Larsson <notifications@github.com>:

Hi is this still a problem?

**Comment by plarsson** [comment]
Not in any easy way that I know of, but if you run it in "developer mode" and install the app with athom CLI you can see the logs.

**Comment by plarsson** [comment]
Please try version 1.1.1 or greater and see if that helps

**Comment by davidkm123** [comment]
Hi Peter,

still its to same:

 

And after test in flow a get this:

 

D.

6. 11. 2019 v 19:59, Peter Larsson <notifications@github.com>:

Please try version 1.1.1 or greater and see if that helps

**Comment by plarsson** [comment]
Hi, sorry the images you have attached seems missing

**Comment by davidkm123** [comment]
Hi, 
![image](https://user-images.githubusercontent.com/38560286/69218978-24cfd900-0b72-11ea-99e7-ba4bbb7eb53c.png)

and

![image](https://user-images.githubusercontent.com/38560286/69218996-2dc0aa80-0b72-11ea-9f23-8288c761ccc9.png)

**Comment by plarsson** [comment]
Hi the command should be `*Z01ON\u000D` but I guess you tested with that earlier?  Also please double check baud rate and parity.

@SiobhanBaynes  Do you have any possibility to test serial communication on your Flex?

**Comment by SiobhanBaynes** [comment]
> ...
> 
> @SiobhanBaynes Do you have any possibility to test serial communication on your Flex?

I don’t at the moment, I could pick up a serial cable quite cheaply but I wouldn’t have a known good configuration to work against.

**Comment by plarsson** [comment]
Please retry with version 1.2.1. Please reopen if this still is a problem.
