### ISSUE TITLE
SDK 3 support for Homey (early 2023) 

### ISSUE THREAD

**Issue by Viksviktor** [plarsson/com.globalcache#9]
First of all, thank you for a great app! itach is a little gem in combination with Homey.

Unfortunately, SDK 2 apps are not supported by new HP2003...

Is there any chance that you have plans on updating your useful app on occasion? Would be much appreciated

**Comment by wentzel** [comment]
Agree! This seems like a great app, thanks for creating it! I'd love to use it, but I would need it with SDK3.0 For it to work with my Homey Pro.

I'd love to update it myself, but when reading the Homey guide on how to update it seems like it will take me a few months to learn everything needed (I'm not a developer but know the basics of programming...)

**Comment by plarsson** [comment]
I will take a look on this, would be nice to get it compatible with latest SDK etc

**Comment by plarsson** [comment]
App is now updated for sdk 3 

See https://homey.app/en-se/app/com.globalcache/Global-Cach%C3%A9/test/ for a test version

**Comment by wentzel** [comment]
Amazing! Thank you so much @plarsson ! I'm trying it out now, but unfortunately I can't seem to add a device. There's a spinner on each of the device types, and clicking either of them doesn't seem to do anything. I tried the config page of the app, but editing the JSON without having successfully added a device doesn't seem to be working either.

![image](https://github.com/plarsson/com.globalcache/assets/2807352/6e408ad6-35c0-4f50-992b-539aaeab9f52)


Am I doing something wrong, or is there a bug do you think?

**Comment by plarsson** [comment]
Pushed version 1.2.1. Please have a look.

**Comment by wentzel** [comment]
Yay! It works like a charm! Thank you so so much @plarsson ! Finally I don't have to crawl under the couch to turn on the receiver again 🤣  (using IP2IR)

**Comment by plarsson** [comment]
version 1.2.1 released on homey app store
